{application,styler,
             [{modules,['Elixir.Styler','Elixir.Styler.Style',
                        'Elixir.Styler.Style.Blocks',
                        'Elixir.Styler.Style.Defs',
                        'Elixir.Styler.Style.Deprecations',
                        'Elixir.Styler.Style.ModuleDirectives',
                        'Elixir.Styler.Style.Pipes',
                        'Elixir.Styler.Style.SingleNode',
                        'Elixir.Styler.StyleError','Elixir.Styler.Zipper']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"A code-style enforcer that will just FIFY instead of complaining"},
              {registered,[]},
              {vsn,"0.11.9"}]}.
