{application,oban_met,
             [{modules,['Elixir.Jason.Encoder.Oban.Met.Values.Gauge',
                        'Elixir.Jason.Encoder.Oban.Met.Values.Sketch',
                        'Elixir.Oban.Met','Elixir.Oban.Met.Application',
                        'Elixir.Oban.Met.Cronitor','Elixir.Oban.Met.Examiner',
                        'Elixir.Oban.Met.Listener','Elixir.Oban.Met.Recorder',
                        'Elixir.Oban.Met.Reporter','Elixir.Oban.Met.Value',
                        'Elixir.Oban.Met.Value.Oban.Met.Values.Gauge',
                        'Elixir.Oban.Met.Value.Oban.Met.Values.Sketch',
                        'Elixir.Oban.Met.Values.Gauge',
                        'Elixir.Oban.Met.Values.Sketch']},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,oban,telemetry]},
              {description,"A distributed, compacting, multidimensional, telemetry-powered time series datastore"},
              {registered,[]},
              {vsn,"0.1.11"},
              {mod,{'Elixir.Oban.Met.Application',[]}},
              {env,[{auto_start,true},{auto_testing_modes,[disabled]}]}]}.
